defaults: &defaults
  working_directory: /home/circleci/pubsub
  docker:
    - image: node:12.10.0
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-package-lock-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: v1-package-lock-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-package-lock-cache-{{ checksum "package-lock.json" }}
      - run:
          name: test
          command: npm run test
      - store_test_results:
          path: log
      - store_artifacts:
          path: log
          destination: log
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-package-lock-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm run lint
          command: npm run lint
      - store_test_results:
          path: log
      - store_artifacts:
          path: log
          destination: log
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
